### ISSUE TITLE
Implement storage module in medusa using moneta

### ISSUE THREAD

**Issue by McOmghall** [brutuscat/medusa-crawler#3]
Migrating this issue from Anemone, can we add a data accessor for this database? Thanks.

**Comment by brutuscat** [comment]
@McOmghall I'm not against it, but personally I'm not familiarised with neo4j. 

To add support for it you can submit a PR implementing a class like all the other [storage implementations](https://github.com/brutuscat/medusa/tree/master/lib/medusa/storage) and its corresponding [spec test](https://github.com/brutuscat/medusa/blob/master/spec/storage_spec.rb)

**Comment by McOmghall** [comment]
I can work on it, I'm reading the modules under [storage implementations](https://github.com/brutuscat/medusa/tree/master/lib/medusa/storage) and I think I understand the basic idea.

I have a question though, do any of these implementations store relationships between pages (links_to type)? It doesn't look like it's in the spec but it's something I'd need.

**Comment by brutuscat** [comment]
@McOmghall I'm not quite sure what u mean, but as far as I can see this is just a plain storage that is treated as an "hash" to access data by key.
Maybe it makes sense to u to have a separate instance of an storage and handle your data model in the "blocks" within your application? Unless you could come up with a real use case for most of this gem users...

Could you please explain your use case more in detail?

**Comment by McOmghall** [comment]
Well, given neo4j is a graph database it makes sense for the nodes to have all the data relevant to a page but the links should be represented as graph edges since they are a relationship between pages. I thought medusa modelled the crawl this way, but since a crawler is just data retrieval I guess it makes sense to just get everything and save it as it is.

How do you specify medusa the data you want to persist? Is it in the main crawling block?

**Comment by brutuscat** [comment]
@McOmghall what if instead of our custom storage we use [moneta](https://github.com/minad/moneta)? It has support for [ActiveRecord](https://github.com/minad/moneta#supported-backends) you u could plug in a neo4J AR adapter...

**Comment by McOmghall** [comment]
I've never used moneta so I can't really say but it seems like a good idea. I've opened the [issue](https://github.com/neo4jrb/neo4j/issues/639) in the neo4j official adapter for ruby

**Comment by ZirconCode** [comment]
@brutuscat +1 on moneta, keeps things flexible and offloads a lot of code

**Comment by McOmghall** [comment]
I've noticed the model we use doesn't apply to my use case needs so I'll implement my own module outside medusa's implementation. I agree implementing the storage module in moneta is a good idea, giving the user more options and giving us the capability to work more on crawling specifics.

I rename this issue.

**Comment by brutuscat** [comment]
Closing as it has been done at https://github.com/brutuscat/medusa/pull/14
